all: main run

main: src/main.cpp 
	g++ -std=c++17 -Iinclude -Iinclude/sdl -Iinclude/headers -Llib -o main.exe src/*.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

run: main
	./main.exe

.PHONY: all run